language: node_js
node_js:
  - "8"
cache:
  directories:
    - "node_modules"
script:
  - npm run pretest
  - npm run covered-test
  - npm run report-coverage

deploy:
  provider: heroku
  api_key: $HEROKU_API_KEY
  app:
    master: server7547
    staging: stagingserver7547