version: '3'

services:
  app:
    build: .
    image: 7547_tp1_server_app
    environment:
      - PORT=3000
      - NODE_ENV=development
    depends_on:
      - postgres
    ports:
      - "3000:3000"
      - "9229:9229"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    links:
      - "postgres:database"
    env_file:
      - process.env
      
  postgres:
    image: debezium/postgres:9.6
    ports:
    - 5432:5432
    environment:
    - POSTGRES_USER=tp1_server_test
    - POSTGRES_PASSWORD=tp1_server_test
    - POSTGRES_DB=tp1_server_test

  migrations:
    image: 7547_tp1_server_app:latest
    command: ["./wait-for-it/wait-for-it.sh", "postgres:5432", "--", "npm", "run", "db:migrate"]
    links:
      - postgres
    depends_on:
      - postgres